CREATE TABLE FOTOGRAFO (
    ID    INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME  VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE LOTE (
    ID           INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FOTOGRAFO_ID INT          NOT NULL,
    SESSAO_ID    INT          NOT NULL,
    SPOT_ID      INT          NOT NULL,
    DESCRICAO    VARCHAR(500) NOT NULL,
    CRIADO_EM    TIMESTAMP    NOT NULL,
    ARQUIVADO    BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE FOTO (
    ID             INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LOTE_ID        INT           NOT NULL,
    URL_PREVIEW    CLOB          NOT NULL,
    URL_ORIGINAL   CLOB          NOT NULL,
    EXIF_TIMESTAMP TIMESTAMP     NOT NULL,
    EXIF_DETALHES  VARCHAR(500)  NOT NULL,
    LICENCIADA     BOOLEAN       NOT NULL DEFAULT FALSE,
    REMOVIDA       BOOLEAN       NOT NULL DEFAULT FALSE
);

CREATE TABLE LICENCA_IMAGEM (
    ID           INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ATLETA_ID    INT           NOT NULL,
    FOTO_ID      INT           NOT NULL,
    PRECO        DECIMAL(10,2) NOT NULL,
    ADQUIRIDA_EM TIMESTAMP     NOT NULL,
    CANCELADA    BOOLEAN       NOT NULL DEFAULT FALSE
);

CREATE TABLE SPLIT_FINANCEIRO (
    ID               INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LICENCA_ID       INT           NOT NULL,
    VALOR_FOTOGRAFO  DECIMAL(10,2) NOT NULL,
    TAXA_PLATAFORMA  DECIMAL(10,2) NOT NULL,
    PROCESSADO_EM    TIMESTAMP     NOT NULL
);

CREATE TABLE FAVORITO (
    ID        INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ATLETA_ID INT NOT NULL,
    FOTO_ID   INT NOT NULL
);
