CREATE TABLE ATLETA (
    ID   INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME  VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE CARTA_OFICIAL (
    ATLETA_ID            INT     NOT NULL PRIMARY KEY,
    OVERALL              DOUBLE  NOT NULL DEFAULT 0,
    ULTIMA_SINCRONIZACAO TIMESTAMP
);

CREATE TABLE ATRIBUTO_ESPORTIVO (
    ID           INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ATLETA_ID    INT           NOT NULL,
    NOME         VARCHAR(255)  NOT NULL,
    VALOR        DOUBLE        NOT NULL,
    PESO         DOUBLE        NOT NULL,
    TIPO_ESPORTE VARCHAR(255)  NOT NULL
);

CREATE TABLE STATUS_POTENCIAL (
    ATLETA_ID            INT    NOT NULL PRIMARY KEY,
    XP_ACUMULADO         DOUBLE NOT NULL DEFAULT 0,
    STREAK_CONSISTENCIA  INT    NOT NULL DEFAULT 0,
    ULTIMA_ATIVIDADE     TIMESTAMP
);

CREATE TABLE LICENCA_GAMIFICATION (
    ID          INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ATLETA_ID   INT       NOT NULL,
    ADQUIRIDA_EM TIMESTAMP NOT NULL
);
