CREATE TABLE PERFIL_SOCIAL (
    ID                INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USUARIO_ID        INT          NOT NULL UNIQUE,
    NOME_EXIBICAO     VARCHAR(255) NOT NULL,
    TIPO_CONTA        VARCHAR(20)  NOT NULL,
    BIO               VARCHAR(300),
    ESPORTE           VARCHAR(100),
    LOCALIDADE        VARCHAR(255),
    VISIBILIDADE      VARCHAR(20)  NOT NULL DEFAULT 'PUBLICA',
    TOTAL_SEGUIDORES  INT          NOT NULL DEFAULT 0,
    TOTAL_SEGUINDO    INT          NOT NULL DEFAULT 0
);

CREATE TABLE CONEXAO_SOCIAL (
    ID          INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SEGUIDOR_ID INT       NOT NULL,
    SEGUIDO_ID  INT       NOT NULL,
    CRIADA_EM   TIMESTAMP NOT NULL,
    UNIQUE (SEGUIDOR_ID, SEGUIDO_ID)
);

CREATE TABLE PEDIDO_CONEXAO (
    ID             INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SOLICITANTE_ID INT          NOT NULL,
    ALVO_ID        INT          NOT NULL,
    CRIADO_EM      TIMESTAMP    NOT NULL,
    STATUS         VARCHAR(20)  NOT NULL DEFAULT 'PENDENTE'
);

CREATE TABLE BLOQUEIO_SOCIAL (
    ID           INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BLOQUEADOR_ID INT NOT NULL,
    BLOQUEADO_ID  INT NOT NULL,
    UNIQUE (BLOQUEADOR_ID, BLOQUEADO_ID)
);
