CREATE TABLE POST_ESPORTIVO (
    ID        INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    AUTOR_ID  INT          NOT NULL,
    CONTEUDO  VARCHAR(500) NOT NULL,
    ESPORTE   VARCHAR(100),
    CRIADO_EM TIMESTAMP    NOT NULL
);
