CREATE TABLE COMENTARIO_FEED (
    ID          INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ITEM_FEED_ID INT         NOT NULL,
    AUTOR_ID    INT         NOT NULL,
    CONTEUDO    VARCHAR(300) NOT NULL,
    PARENT_ID   INT,
    CRIADO_EM   TIMESTAMP   NOT NULL
);
