CREATE TABLE MENSAGEM_DIRETA (
    ID              INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    REMETENTE_ID    INT          NOT NULL,
    DESTINATARIO_ID INT          NOT NULL,
    CONTEUDO        VARCHAR(1000) NOT NULL,
    LIDA            BOOLEAN      NOT NULL DEFAULT FALSE,
    CRIADA_EM       TIMESTAMP    NOT NULL
);
