-- Funcionalidade 1: Carta Oficial com Progressao (Tier/Reveal) e Ranking Competitivo

-- Extensao da Carta: tier, saldo de pontos do Reveal e arquivamento
ALTER TABLE CARTA_OFICIAL ADD COLUMN TIER VARCHAR(20) NOT NULL DEFAULT 'BRONZE';
ALTER TABLE CARTA_OFICIAL ADD COLUMN SALDO_PONTOS DOUBLE NOT NULL DEFAULT 0;
ALTER TABLE CARTA_OFICIAL ADD COLUMN ARQUIVADA BOOLEAN NOT NULL DEFAULT FALSE;

-- Historico de evolucao (append-only) do Overall
CREATE TABLE REGISTRO_EVOLUCAO (
    ID               INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ATLETA_ID        INT       NOT NULL,
    OVERALL_ANTERIOR DOUBLE    NOT NULL,
    OVERALL_NOVO     DOUBLE    NOT NULL,
    OCORRIDO_EM      TIMESTAMP NOT NULL
);

-- Registro de cada Sincronizacao (Reveal) confirmada
CREATE TABLE REGISTRO_SINCRONIZACAO (
    ID               INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ATLETA_ID        INT       NOT NULL,
    OCORRIDO_EM      TIMESTAMP NOT NULL,
    ORCAMENTO_PONTOS INT       NOT NULL,
    CUSTO_TOTAL      INT       NOT NULL,
    OVERALL_ANTERIOR DOUBLE    NOT NULL,
    OVERALL_NOVO     DOUBLE    NOT NULL
);

CREATE TABLE REGISTRO_SINC_ALOCACAO (
    REGISTRO_ID INT          NOT NULL,
    ATRIBUTO    VARCHAR(255) NOT NULL,
    INCREMENTO  INT          NOT NULL
);

-- Pontuacao de Ranking (PR) por atleta
CREATE TABLE PONTUACAO_RANKING (
    ATLETA_ID      INT    NOT NULL PRIMARY KEY,
    PR             DOUBLE NOT NULL DEFAULT 0,
    ULTIMA_PARTIDA TIMESTAMP
);

-- Confrontos resolvidos
CREATE TABLE CONFRONTO (
    ID             INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VENCEDOR_ID    INT       NOT NULL,
    PERDEDOR_ID    INT       NOT NULL,
    PR_TRANSFERIDA DOUBLE    NOT NULL,
    OCORRIDO_EM    TIMESTAMP NOT NULL,
    TEMPORADA_ID   INT       NOT NULL
);

-- Temporadas e seus snapshots finais
CREATE TABLE TEMPORADA (
    ID         INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MODALIDADE VARCHAR(255) NOT NULL,
    INICIO     TIMESTAMP    NOT NULL,
    FIM        TIMESTAMP    NOT NULL,
    STATUS     VARCHAR(20)  NOT NULL
);

CREATE TABLE TEMPORADA_SNAPSHOT (
    TEMPORADA_ID INT    NOT NULL,
    ATLETA_ID    INT    NOT NULL,
    POSICAO      INT    NOT NULL,
    PR           DOUBLE NOT NULL
);
