CREATE TABLE ITEM_FEED (
    ID           INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    AUTOR_ID     INT          NOT NULL,
    TIPO         VARCHAR(30)  NOT NULL,
    REFERENCIA_ID INT         NOT NULL DEFAULT 0,
    PUBLICADO_EM TIMESTAMP    NOT NULL
);

CREATE TABLE CURTIDA_FEED (
    ID         INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USUARIO_ID INT NOT NULL,
    ITEM_ID    INT NOT NULL,
    UNIQUE (USUARIO_ID, ITEM_ID)
);

CREATE TABLE NOTIFICACAO_SOCIAL (
    ID              INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESTINATARIO_ID INT          NOT NULL,
    TIPO            VARCHAR(30)  NOT NULL,
    REFERENCIA_ID   INT          NOT NULL DEFAULT 0,
    LIDA            BOOLEAN      NOT NULL DEFAULT FALSE,
    CRIADA_EM       TIMESTAMP    NOT NULL,
    NUM_ATORES      INT          NOT NULL DEFAULT 1
);
