-- Funcionalidade 2: Motor de Desafios (Quests) e Insignias

CREATE TABLE DESAFIO (
    ID              INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITULO          VARCHAR(255) NOT NULL,
    INICIO          TIMESTAMP,
    FIM             TIMESTAMP,
    PERMANENTE      BOOLEAN      NOT NULL DEFAULT FALSE,
    INSIGNIA_CODIGO VARCHAR(255) NOT NULL,
    CADENCIA        VARCHAR(20)  NOT NULL,
    REPETIVEL       BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE DESAFIO_CRITERIO (
    DESAFIO_ID    INT          NOT NULL,
    ORDEM         INT          NOT NULL,
    TIPO          VARCHAR(40)  NOT NULL,
    META          INT          NOT NULL,
    ALVO_ATRIBUTO VARCHAR(255)
);

CREATE TABLE DESAFIO_PREREQUISITO (
    DESAFIO_ID      INT NOT NULL,
    PREREQUISITO_ID INT NOT NULL
);

CREATE TABLE PROGRESSO_DESAFIO (
    ID                 INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ATLETA_ID          INT         NOT NULL,
    DESAFIO_ID         INT         NOT NULL,
    STATUS             VARCHAR(20) NOT NULL,
    INSIGNIA_CONCEDIDA BOOLEAN     NOT NULL DEFAULT FALSE,
    CICLO_REFERENCIA   DATE,
    INICIADO_EM        TIMESTAMP   NOT NULL
);

CREATE TABLE PROGRESSO_CONTADOR (
    PROGRESSO_ID    INT NOT NULL,
    CRITERIO_INDICE INT NOT NULL,
    CONTADOR        INT NOT NULL
);

CREATE TABLE INSIGNIA (
    ID           INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ATLETA_ID    INT          NOT NULL,
    CODIGO       VARCHAR(255) NOT NULL,
    DESAFIO_ID   INT          NOT NULL,
    CONCEDIDA_EM TIMESTAMP    NOT NULL
);
