CREATE TABLE SPOT (
    ID        INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME      VARCHAR(255)  NOT NULL,
    LATITUDE  DOUBLE        NOT NULL,
    LONGITUDE DOUBLE        NOT NULL,
    DESCRICAO VARCHAR(1000)
);

CREATE TABLE SESSAO (
    ID             INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SPOT_ID        INT          NOT NULL,
    PERIODO_INICIO TIMESTAMP    NOT NULL,
    PERIODO_FIM    TIMESTAMP    NOT NULL,
    DESCRICAO      VARCHAR(500) NOT NULL,
    CANCELADA      BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE CHECK_IN (
    ID                   INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ATLETA_ID            INT       NOT NULL,
    SESSAO_ID            INT       NOT NULL,
    HORARIO              TIMESTAMP NOT NULL,
    LATITUDE             DOUBLE    NOT NULL,
    LONGITUDE            DOUBLE    NOT NULL,
    CANCELADO            BOOLEAN   NOT NULL DEFAULT FALSE,
    ATIVIDADE_REGISTRADA BOOLEAN   NOT NULL DEFAULT FALSE
);

CREATE TABLE REGISTRO_ATIVIDADE (
    ID               INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CHECK_IN_ID      INT    NOT NULL,
    DISTANCIA        DOUBLE NOT NULL,
    DURACAO_SEGUNDOS BIGINT NOT NULL,
    INTENSIDADE      VARCHAR(20) NOT NULL,
    XP_CALCULADO     DOUBLE NOT NULL
);
