ALTER TABLE REGISTRO_ATIVIDADE ADD COLUMN ATLETA_ID INT;
UPDATE REGISTRO_ATIVIDADE r SET ATLETA_ID = (SELECT c.ATLETA_ID FROM CHECK_IN c WHERE c.ID = r.CHECK_IN_ID);
ALTER TABLE REGISTRO_ATIVIDADE ALTER COLUMN ATLETA_ID SET NOT NULL;

ALTER TABLE REGISTRO_ATIVIDADE ALTER COLUMN CHECK_IN_ID DROP NOT NULL;
ALTER TABLE REGISTRO_ATIVIDADE ALTER COLUMN INTENSIDADE DROP NOT NULL;
ALTER TABLE REGISTRO_ATIVIDADE ALTER COLUMN XP_CALCULADO DROP NOT NULL;

ALTER TABLE REGISTRO_ATIVIDADE ADD COLUMN ESPORTE VARCHAR(50);
ALTER TABLE REGISTRO_ATIVIDADE ADD COLUMN DATA TIMESTAMP;
ALTER TABLE REGISTRO_ATIVIDADE ADD COLUMN ESFORCO_PERCEBIDO INT;
ALTER TABLE REGISTRO_ATIVIDADE ADD COLUMN OBSERVACOES VARCHAR(1000);
ALTER TABLE REGISTRO_ATIVIDADE ADD COLUMN ORIGEM_REGISTRO VARCHAR(20);
ALTER TABLE REGISTRO_ATIVIDADE ADD COLUMN METRICAS VARCHAR(2000);
ALTER TABLE REGISTRO_ATIVIDADE ADD COLUMN CRIADO_EM TIMESTAMP;
ALTER TABLE REGISTRO_ATIVIDADE ADD COLUMN ATUALIZADO_EM TIMESTAMP;

UPDATE REGISTRO_ATIVIDADE SET ORIGEM_REGISTRO = 'CHECKIN' WHERE ORIGEM_REGISTRO IS NULL;
UPDATE REGISTRO_ATIVIDADE SET ESPORTE = 'CORRIDA' WHERE ESPORTE IS NULL;
UPDATE REGISTRO_ATIVIDADE r SET DATA = (SELECT c.HORARIO FROM CHECK_IN c WHERE c.ID = r.CHECK_IN_ID) WHERE DATA IS NULL;
UPDATE REGISTRO_ATIVIDADE SET CRIADO_EM = CURRENT_TIMESTAMP WHERE CRIADO_EM IS NULL;
UPDATE REGISTRO_ATIVIDADE SET ATUALIZADO_EM = CURRENT_TIMESTAMP WHERE ATUALIZADO_EM IS NULL;
